algoritmo "SOMA-PROCEDIMENTO"
var
X, Y : INTEIRO

//----------------------------------------------------------
Procedimento Soma(A,B: INTEIRO)
Inicio
      Escreval("Recebi o valor: ", A)
      Escreval("Recebi o valor: ", B)
      Escreval("A soma entre os dois valores é: ", A + B)
FimProcedimento
//----------------------------------------------------------

inicio
 X <- 5
 Y <- 3
 Soma(X,Y)
fimalgoritmo